import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast"
import { GardenProvider } from "@/context/GardenContext"
import { PermissionProvider } from "@/context/PermissionContext"
import { UserProvider } from "@/context/UserContext"
import Script from "next/script"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <GardenProvider>
            <PermissionProvider>
            <Toaster />
            {children}
            <Script
              src="https://widget.cloudinary.com/v2.0/global/all.js"
              strategy="afterInteractive"
            />
            </PermissionProvider>
          </GardenProvider>
        </UserProvider>
      </body>
    </html>
  );
}
